changelog:
  exclude:
    authors:
      - mc2center-bot
  categories:
    - title: New changes
      labels:
        - '*'
      exclude:
        labels:
          - bug
          - misc
    - title: Bug fixes
      labels:
        - bug
    - title: Compatible with DCA/schematic versions
      labels:
        - misc
